### ISSUE TITLE
Unit test fails after upgrading v0.14.6 from 0.12.29

### ISSUE THREAD

**Issue by cosmo0920** [tagomoris/fluent-plugin-datacounter#16]
With 0.12.29

```log
% bundle exec rake test
<snip>
Finished in 7.916504144668579 seconds.
--------------------------------------------------------------------------------
13 tests, 248 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------
1.64 tests/s, 31.33 assertions/s
```

With 0.14.6

```log
$ bundle exec rake test
/Users/hhatake/.rbenv/versions/2.3.0/bin/ruby -w -I"lib:lib:test" -I"/Users/hhatake/Github/fluent-plugin-datacounter/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib" "/Users/hhatake/Github/fluent-plugin-datacounter/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb" "test/**/test_*.rb" 
<snip>
Loaded suite /Users/hhatake/Github/fluent-plugin-datacounter/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader
Started
.........F
================================================================================
Failure: test_store_file(DataCounterOutputTest)
/Users/hhatake/Github/fluent-plugin-datacounter/test/plugin/test_out_datacounter.rb:706:in `block in test_store_file'
     703:       loaded_counts = d.instance.counts
     704:       loaded_saved_at = d.instance.saved_at
     705:       loaded_saved_duration = d.instance.saved_duration
  => 706:       assert_equal({}, loaded_counts)
     707:       assert_equal(nil, loaded_saved_at)
     708:       assert_equal(nil, loaded_saved_duration)
     709:     end
/Users/hhatake/Github/fluent-plugin-datacounter/vendor/bundle/ruby/2.3.0/gems/fluentd-0.14.6/lib/fluent/test/input_test.rb:123:in `block in run'
/Users/hhatake/Github/fluent-plugin-datacounter/vendor/bundle/ruby/2.3.0/gems/fluentd-0.14.6/lib/fluent/test/base.rb:71:in `run'
/Users/hhatake/Github/fluent-plugin-datacounter/vendor/bundle/ruby/2.3.0/gems/fluentd-0.14.6/lib/fluent/test/input_test.rb:122:in `run'
/Users/hhatake/Github/fluent-plugin-datacounter/test/plugin/test_out_datacounter.rb:702:in `test_store_file'
<{}> expected but was
<{"test.input"=>[3, 0, 0, 0, 0, 3]}>

diff:
? {"test.input"=>[3, 0, 0, 0, 0, 3]}
================================================================================
...

Finished in 68.84033346176147 seconds.
--------------------------------------------------------------------------------
13 tests, 246 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
92.3077% passed
--------------------------------------------------------------------------------
0.19 tests/s, 3.57 assertions/s
rake aborted!
```

I have no idea what causes this failure, though.... :/

**Comment by cosmo0920** [comment]
memo: We should use storage_local plugin to support this storing feature when migrating to v0.14 API.

**Comment by cosmo0920** [comment]
Additional memo: I've found that using `storage_local` plugin does not achieve absorbing difference between v0.12 and v0.14 behaviour.
This plugin should store Ruby Object which is not encodable into JSON.

The following thing should be saved with Marshaling:

`@pattern`: https://github.com/tagomoris/fluent-plugin-datacounter/blob/master/lib/fluent/plugin/out_datacounter.rb#L91

How do we treat marshaling in this plugin on v0.14 migration? :confounded:

**Comment by tagomoris** [comment]
IMO, storing regular expression strings looks to satisfy what is needed. Are there any problem?

**Comment by cosmo0920** [comment]
Umm..., once I think so.
But, I found that storing regular expression strings via storage_local plugin makes broken regular expression strings, like:

```log
{"counts"=>{"test.input"=>[0, 0, 0, 0, 0, 0]}, "saved_at"=>1479954391, "saved_duration"=>0, "aggregate"=>"tag", "count_key"=>" target", "patterns"=>"[[0, \"unmatched\", nil], [1, \"status2xx\", /^2\\d\\d$/], [2, \"status3xx\", /^3\\d\\d$/], [3, \"status4xx\", /^4\\d\\d$/], [4, \"status5xx\", /^5\\d\\d$/]]"}
```

They are totally escaped to be valid JSON strings object.

**Comment by cosmo0920** [comment]
Above comment is my misunderstanding.
Sorry for noise. :sweat:
